/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOrchestrator,
  IOrchestratorInterface,
} from "../../../contracts/interfaces/IOrchestrator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "existingIntent",
        type: "bytes32",
      },
    ],
    name: "AccountHasActiveIntent",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "max",
        type: "uint256",
      },
    ],
    name: "AmountAboveMax",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "min",
        type: "uint256",
      },
    ],
    name: "AmountBelowMin",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
    ],
    name: "AmountExceedsLimit",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentMethod",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "currency",
        type: "bytes32",
      },
    ],
    name: "CurrencyNotSupported",
    type: "error",
  },
  {
    inputs: [],
    name: "EscrowLockFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "escrow",
        type: "address",
      },
    ],
    name: "EscrowNotWhitelisted",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maximum",
        type: "uint256",
      },
    ],
    name: "FeeExceedsMaximum",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "expected",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "actual",
        type: "bytes32",
      },
    ],
    name: "HashMismatch",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "intentHash",
        type: "bytes32",
      },
    ],
    name: "IntentNotFound",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidReferrerFeeConfiguration",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidSignature",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "currentTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "allowedTime",
        type: "uint256",
      },
    ],
    name: "PartialReleaseNotAllowedYet",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentMethod",
        type: "bytes32",
      },
    ],
    name: "PaymentMethodDoesNotExist",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentMethod",
        type: "bytes32",
      },
    ],
    name: "PaymentMethodNotSupported",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "paymentMethod",
        type: "bytes32",
      },
    ],
    name: "PaymentMethodNotWhitelisted",
    type: "error",
  },
  {
    inputs: [],
    name: "PaymentVerificationFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "hook",
        type: "address",
      },
    ],
    name: "PostIntentHookNotWhitelisted",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "rate",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minRate",
        type: "uint256",
      },
    ],
    name: "RateBelowMinimum",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "expiration",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "currentTime",
        type: "uint256",
      },
    ],
    name: "SignatureExpired",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "TransferFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        internalType: "address",
        name: "authorized",
        type: "address",
      },
    ],
    name: "UnauthorizedCaller",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "UnauthorizedEscrowCaller",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroValue",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool",
        name: "allowMultiple",
        type: "bool",
      },
    ],
    name: "AllowMultipleIntentsUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "escrowRegistry",
        type: "address",
      },
    ],
    name: "EscrowRegistryUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "intentHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "fundsTransferredTo",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isManualRelease",
        type: "bool",
      },
    ],
    name: "IntentFulfilled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "intentHash",
        type: "bytes32",
      },
    ],
    name: "IntentPruned",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "intentHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "escrow",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "depositId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "paymentMethod",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "fiatCurrency",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "conversionRate",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "IntentSignaled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "partialManualReleaseDelay",
        type: "uint256",
      },
    ],
    name: "PartialManualReleaseDelayUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "paymentVerifierRegistry",
        type: "address",
      },
    ],
    name: "PaymentVerifierRegistryUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "postIntentHookRegistry",
        type: "address",
      },
    ],
    name: "PostIntentHookRegistryUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "protocolFeeRecipient",
        type: "address",
      },
    ],
    name: "ProtocolFeeRecipientUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "protocolFee",
        type: "uint256",
      },
    ],
    name: "ProtocolFeeUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "relayerRegistry",
        type: "address",
      },
    ],
    name: "RelayerRegistryUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "intentHash",
        type: "bytes32",
      },
    ],
    name: "cancelIntent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "bytes",
            name: "paymentProof",
            type: "bytes",
          },
          {
            internalType: "bytes32",
            name: "intentHash",
            type: "bytes32",
          },
          {
            internalType: "bytes",
            name: "verificationData",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "postIntentHookData",
            type: "bytes",
          },
        ],
        internalType: "struct IOrchestrator.FulfillIntentParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "fulfillIntent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "getAccountIntents",
    outputs: [
      {
        internalType: "bytes32[]",
        name: "",
        type: "bytes32[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "intentHash",
        type: "bytes32",
      },
    ],
    name: "getIntent",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "address",
            name: "escrow",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "depositId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "paymentMethod",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "fiatCurrency",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "conversionRate",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "payeeId",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "referrer",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "referrerFee",
            type: "uint256",
          },
          {
            internalType: "contract IPostIntentHook",
            name: "postIntentHook",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct IOrchestrator.Intent",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "intentIds",
        type: "bytes32[]",
      },
    ],
    name: "pruneIntents",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "intentHash",
        type: "bytes32",
      },
    ],
    name: "releaseFundsToPayer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "escrow",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "depositId",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "bytes32",
            name: "paymentMethod",
            type: "bytes32",
          },
          {
            internalType: "bytes32",
            name: "fiatCurrency",
            type: "bytes32",
          },
          {
            internalType: "uint256",
            name: "conversionRate",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "referrer",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "referrerFee",
            type: "uint256",
          },
          {
            internalType: "bytes",
            name: "gatingServiceSignature",
            type: "bytes",
          },
          {
            internalType: "uint256",
            name: "signatureExpiration",
            type: "uint256",
          },
          {
            internalType: "contract IPostIntentHook",
            name: "postIntentHook",
            type: "address",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct IOrchestrator.SignalIntentParams",
        name: "params",
        type: "tuple",
      },
    ],
    name: "signalIntent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOrchestrator__factory {
  static readonly abi = _abi;
  static createInterface(): IOrchestratorInterface {
    return new utils.Interface(_abi) as IOrchestratorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOrchestrator {
    return new Contract(address, _abi, signerOrProvider) as IOrchestrator;
  }
}
