/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IProtocolViewerV2,
  IProtocolViewerV2Interface,
} from "../../../contracts/interfaces/IProtocolViewerV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_orchestrator",
        type: "address",
      },
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "getAccountIntents",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "intentHash",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "address",
                name: "owner",
                type: "address",
              },
              {
                internalType: "address",
                name: "to",
                type: "address",
              },
              {
                internalType: "address",
                name: "escrow",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "depositId",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "timestamp",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "paymentMethod",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "fiatCurrency",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "conversionRate",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "payeeId",
                type: "bytes32",
              },
              {
                internalType: "address",
                name: "referrer",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "referrerFee",
                type: "uint256",
              },
              {
                internalType: "contract IPostIntentHookV2",
                name: "postIntentHook",
                type: "address",
              },
              {
                internalType: "bytes",
                name: "data",
                type: "bytes",
              },
            ],
            internalType: "struct IOrchestratorV2.Intent",
            name: "intent",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "depositId",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "depositor",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "delegate",
                    type: "address",
                  },
                  {
                    internalType: "contract IERC20",
                    name: "token",
                    type: "address",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "min",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "max",
                        type: "uint256",
                      },
                    ],
                    internalType: "struct IEscrow.Range",
                    name: "intentAmountRange",
                    type: "tuple",
                  },
                  {
                    internalType: "bool",
                    name: "acceptingIntents",
                    type: "bool",
                  },
                  {
                    internalType: "uint256",
                    name: "remainingDeposits",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "outstandingIntentAmount",
                    type: "uint256",
                  },
                  {
                    internalType: "address",
                    name: "intentGuardian",
                    type: "address",
                  },
                  {
                    internalType: "bool",
                    name: "retainOnEmpty",
                    type: "bool",
                  },
                ],
                internalType: "struct IEscrow.Deposit",
                name: "deposit",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "availableLiquidity",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "paymentMethod",
                    type: "bytes32",
                  },
                  {
                    components: [
                      {
                        internalType: "address",
                        name: "intentGatingService",
                        type: "address",
                      },
                      {
                        internalType: "bytes32",
                        name: "payeeDetails",
                        type: "bytes32",
                      },
                      {
                        internalType: "bytes",
                        name: "data",
                        type: "bytes",
                      },
                    ],
                    internalType: "struct IEscrow.DepositPaymentMethodData",
                    name: "verificationData",
                    type: "tuple",
                  },
                  {
                    components: [
                      {
                        internalType: "bytes32",
                        name: "code",
                        type: "bytes32",
                      },
                      {
                        internalType: "uint256",
                        name: "minConversionRate",
                        type: "uint256",
                      },
                    ],
                    internalType: "struct IEscrow.Currency[]",
                    name: "currencies",
                    type: "tuple[]",
                  },
                ],
                internalType:
                  "struct IProtocolViewerV2.PaymentMethodDataView[]",
                name: "paymentMethods",
                type: "tuple[]",
              },
              {
                internalType: "bytes32[]",
                name: "intentHashes",
                type: "bytes32[]",
              },
            ],
            internalType: "struct IProtocolViewerV2.DepositView",
            name: "deposit",
            type: "tuple",
          },
        ],
        internalType: "struct IProtocolViewerV2.IntentView[]",
        name: "intentViews",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_escrow",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_depositId",
        type: "uint256",
      },
    ],
    name: "getDeposit",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "depositId",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "address",
                name: "depositor",
                type: "address",
              },
              {
                internalType: "address",
                name: "delegate",
                type: "address",
              },
              {
                internalType: "contract IERC20",
                name: "token",
                type: "address",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "min",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "max",
                    type: "uint256",
                  },
                ],
                internalType: "struct IEscrow.Range",
                name: "intentAmountRange",
                type: "tuple",
              },
              {
                internalType: "bool",
                name: "acceptingIntents",
                type: "bool",
              },
              {
                internalType: "uint256",
                name: "remainingDeposits",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "outstandingIntentAmount",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "intentGuardian",
                type: "address",
              },
              {
                internalType: "bool",
                name: "retainOnEmpty",
                type: "bool",
              },
            ],
            internalType: "struct IEscrow.Deposit",
            name: "deposit",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "availableLiquidity",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "paymentMethod",
                type: "bytes32",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "intentGatingService",
                    type: "address",
                  },
                  {
                    internalType: "bytes32",
                    name: "payeeDetails",
                    type: "bytes32",
                  },
                  {
                    internalType: "bytes",
                    name: "data",
                    type: "bytes",
                  },
                ],
                internalType: "struct IEscrow.DepositPaymentMethodData",
                name: "verificationData",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "code",
                    type: "bytes32",
                  },
                  {
                    internalType: "uint256",
                    name: "minConversionRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct IEscrow.Currency[]",
                name: "currencies",
                type: "tuple[]",
              },
            ],
            internalType: "struct IProtocolViewerV2.PaymentMethodDataView[]",
            name: "paymentMethods",
            type: "tuple[]",
          },
          {
            internalType: "bytes32[]",
            name: "intentHashes",
            type: "bytes32[]",
          },
        ],
        internalType: "struct IProtocolViewerV2.DepositView",
        name: "depositView",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_escrow",
        type: "address",
      },
      {
        internalType: "uint256[]",
        name: "_depositIds",
        type: "uint256[]",
      },
    ],
    name: "getDepositFromIds",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "depositId",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "address",
                name: "depositor",
                type: "address",
              },
              {
                internalType: "address",
                name: "delegate",
                type: "address",
              },
              {
                internalType: "contract IERC20",
                name: "token",
                type: "address",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "min",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "max",
                    type: "uint256",
                  },
                ],
                internalType: "struct IEscrow.Range",
                name: "intentAmountRange",
                type: "tuple",
              },
              {
                internalType: "bool",
                name: "acceptingIntents",
                type: "bool",
              },
              {
                internalType: "uint256",
                name: "remainingDeposits",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "outstandingIntentAmount",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "intentGuardian",
                type: "address",
              },
              {
                internalType: "bool",
                name: "retainOnEmpty",
                type: "bool",
              },
            ],
            internalType: "struct IEscrow.Deposit",
            name: "deposit",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "availableLiquidity",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "bytes32",
                name: "paymentMethod",
                type: "bytes32",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "intentGatingService",
                    type: "address",
                  },
                  {
                    internalType: "bytes32",
                    name: "payeeDetails",
                    type: "bytes32",
                  },
                  {
                    internalType: "bytes",
                    name: "data",
                    type: "bytes",
                  },
                ],
                internalType: "struct IEscrow.DepositPaymentMethodData",
                name: "verificationData",
                type: "tuple",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "code",
                    type: "bytes32",
                  },
                  {
                    internalType: "uint256",
                    name: "minConversionRate",
                    type: "uint256",
                  },
                ],
                internalType: "struct IEscrow.Currency[]",
                name: "currencies",
                type: "tuple[]",
              },
            ],
            internalType: "struct IProtocolViewerV2.PaymentMethodDataView[]",
            name: "paymentMethods",
            type: "tuple[]",
          },
          {
            internalType: "bytes32[]",
            name: "intentHashes",
            type: "bytes32[]",
          },
        ],
        internalType: "struct IProtocolViewerV2.DepositView[]",
        name: "depositArray",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_orchestrator",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "_intentHash",
        type: "bytes32",
      },
    ],
    name: "getIntent",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "intentHash",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "address",
                name: "owner",
                type: "address",
              },
              {
                internalType: "address",
                name: "to",
                type: "address",
              },
              {
                internalType: "address",
                name: "escrow",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "depositId",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "timestamp",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "paymentMethod",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "fiatCurrency",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "conversionRate",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "payeeId",
                type: "bytes32",
              },
              {
                internalType: "address",
                name: "referrer",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "referrerFee",
                type: "uint256",
              },
              {
                internalType: "contract IPostIntentHookV2",
                name: "postIntentHook",
                type: "address",
              },
              {
                internalType: "bytes",
                name: "data",
                type: "bytes",
              },
            ],
            internalType: "struct IOrchestratorV2.Intent",
            name: "intent",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "depositId",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "depositor",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "delegate",
                    type: "address",
                  },
                  {
                    internalType: "contract IERC20",
                    name: "token",
                    type: "address",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "min",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "max",
                        type: "uint256",
                      },
                    ],
                    internalType: "struct IEscrow.Range",
                    name: "intentAmountRange",
                    type: "tuple",
                  },
                  {
                    internalType: "bool",
                    name: "acceptingIntents",
                    type: "bool",
                  },
                  {
                    internalType: "uint256",
                    name: "remainingDeposits",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "outstandingIntentAmount",
                    type: "uint256",
                  },
                  {
                    internalType: "address",
                    name: "intentGuardian",
                    type: "address",
                  },
                  {
                    internalType: "bool",
                    name: "retainOnEmpty",
                    type: "bool",
                  },
                ],
                internalType: "struct IEscrow.Deposit",
                name: "deposit",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "availableLiquidity",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "paymentMethod",
                    type: "bytes32",
                  },
                  {
                    components: [
                      {
                        internalType: "address",
                        name: "intentGatingService",
                        type: "address",
                      },
                      {
                        internalType: "bytes32",
                        name: "payeeDetails",
                        type: "bytes32",
                      },
                      {
                        internalType: "bytes",
                        name: "data",
                        type: "bytes",
                      },
                    ],
                    internalType: "struct IEscrow.DepositPaymentMethodData",
                    name: "verificationData",
                    type: "tuple",
                  },
                  {
                    components: [
                      {
                        internalType: "bytes32",
                        name: "code",
                        type: "bytes32",
                      },
                      {
                        internalType: "uint256",
                        name: "minConversionRate",
                        type: "uint256",
                      },
                    ],
                    internalType: "struct IEscrow.Currency[]",
                    name: "currencies",
                    type: "tuple[]",
                  },
                ],
                internalType:
                  "struct IProtocolViewerV2.PaymentMethodDataView[]",
                name: "paymentMethods",
                type: "tuple[]",
              },
              {
                internalType: "bytes32[]",
                name: "intentHashes",
                type: "bytes32[]",
              },
            ],
            internalType: "struct IProtocolViewerV2.DepositView",
            name: "deposit",
            type: "tuple",
          },
        ],
        internalType: "struct IProtocolViewerV2.IntentView",
        name: "intentView",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_orchestrator",
        type: "address",
      },
      {
        internalType: "bytes32[]",
        name: "_intentHashes",
        type: "bytes32[]",
      },
    ],
    name: "getIntents",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "intentHash",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "address",
                name: "owner",
                type: "address",
              },
              {
                internalType: "address",
                name: "to",
                type: "address",
              },
              {
                internalType: "address",
                name: "escrow",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "depositId",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "timestamp",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "paymentMethod",
                type: "bytes32",
              },
              {
                internalType: "bytes32",
                name: "fiatCurrency",
                type: "bytes32",
              },
              {
                internalType: "uint256",
                name: "conversionRate",
                type: "uint256",
              },
              {
                internalType: "bytes32",
                name: "payeeId",
                type: "bytes32",
              },
              {
                internalType: "address",
                name: "referrer",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "referrerFee",
                type: "uint256",
              },
              {
                internalType: "contract IPostIntentHookV2",
                name: "postIntentHook",
                type: "address",
              },
              {
                internalType: "bytes",
                name: "data",
                type: "bytes",
              },
            ],
            internalType: "struct IOrchestratorV2.Intent",
            name: "intent",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "depositId",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "address",
                    name: "depositor",
                    type: "address",
                  },
                  {
                    internalType: "address",
                    name: "delegate",
                    type: "address",
                  },
                  {
                    internalType: "contract IERC20",
                    name: "token",
                    type: "address",
                  },
                  {
                    components: [
                      {
                        internalType: "uint256",
                        name: "min",
                        type: "uint256",
                      },
                      {
                        internalType: "uint256",
                        name: "max",
                        type: "uint256",
                      },
                    ],
                    internalType: "struct IEscrow.Range",
                    name: "intentAmountRange",
                    type: "tuple",
                  },
                  {
                    internalType: "bool",
                    name: "acceptingIntents",
                    type: "bool",
                  },
                  {
                    internalType: "uint256",
                    name: "remainingDeposits",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "outstandingIntentAmount",
                    type: "uint256",
                  },
                  {
                    internalType: "address",
                    name: "intentGuardian",
                    type: "address",
                  },
                  {
                    internalType: "bool",
                    name: "retainOnEmpty",
                    type: "bool",
                  },
                ],
                internalType: "struct IEscrow.Deposit",
                name: "deposit",
                type: "tuple",
              },
              {
                internalType: "uint256",
                name: "availableLiquidity",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "bytes32",
                    name: "paymentMethod",
                    type: "bytes32",
                  },
                  {
                    components: [
                      {
                        internalType: "address",
                        name: "intentGatingService",
                        type: "address",
                      },
                      {
                        internalType: "bytes32",
                        name: "payeeDetails",
                        type: "bytes32",
                      },
                      {
                        internalType: "bytes",
                        name: "data",
                        type: "bytes",
                      },
                    ],
                    internalType: "struct IEscrow.DepositPaymentMethodData",
                    name: "verificationData",
                    type: "tuple",
                  },
                  {
                    components: [
                      {
                        internalType: "bytes32",
                        name: "code",
                        type: "bytes32",
                      },
                      {
                        internalType: "uint256",
                        name: "minConversionRate",
                        type: "uint256",
                      },
                    ],
                    internalType: "struct IEscrow.Currency[]",
                    name: "currencies",
                    type: "tuple[]",
                  },
                ],
                internalType:
                  "struct IProtocolViewerV2.PaymentMethodDataView[]",
                name: "paymentMethods",
                type: "tuple[]",
              },
              {
                internalType: "bytes32[]",
                name: "intentHashes",
                type: "bytes32[]",
              },
            ],
            internalType: "struct IProtocolViewerV2.DepositView",
            name: "deposit",
            type: "tuple",
          },
        ],
        internalType: "struct IProtocolViewerV2.IntentView[]",
        name: "intentArray",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProtocolViewerV2__factory {
  static readonly abi = _abi;
  static createInterface(): IProtocolViewerV2Interface {
    return new utils.Interface(_abi) as IProtocolViewerV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IProtocolViewerV2 {
    return new Contract(address, _abi, signerOrProvider) as IProtocolViewerV2;
  }
}
