/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace IOrchestrator {
  export type FulfillIntentParamsStruct = {
    paymentProof: PromiseOrValue<BytesLike>;
    intentHash: PromiseOrValue<BytesLike>;
    verificationData: PromiseOrValue<BytesLike>;
    postIntentHookData: PromiseOrValue<BytesLike>;
  };

  export type FulfillIntentParamsStructOutput = [
    string,
    string,
    string,
    string
  ] & {
    paymentProof: string;
    intentHash: string;
    verificationData: string;
    postIntentHookData: string;
  };

  export type IntentStruct = {
    owner: PromiseOrValue<string>;
    to: PromiseOrValue<string>;
    escrow: PromiseOrValue<string>;
    depositId: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    timestamp: PromiseOrValue<BigNumberish>;
    paymentMethod: PromiseOrValue<BytesLike>;
    fiatCurrency: PromiseOrValue<BytesLike>;
    conversionRate: PromiseOrValue<BigNumberish>;
    payeeId: PromiseOrValue<BytesLike>;
    referrer: PromiseOrValue<string>;
    referrerFee: PromiseOrValue<BigNumberish>;
    postIntentHook: PromiseOrValue<string>;
    data: PromiseOrValue<BytesLike>;
  };

  export type IntentStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    string
  ] & {
    owner: string;
    to: string;
    escrow: string;
    depositId: BigNumber;
    amount: BigNumber;
    timestamp: BigNumber;
    paymentMethod: string;
    fiatCurrency: string;
    conversionRate: BigNumber;
    payeeId: string;
    referrer: string;
    referrerFee: BigNumber;
    postIntentHook: string;
    data: string;
  };

  export type SignalIntentParamsStruct = {
    escrow: PromiseOrValue<string>;
    depositId: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    to: PromiseOrValue<string>;
    paymentMethod: PromiseOrValue<BytesLike>;
    fiatCurrency: PromiseOrValue<BytesLike>;
    conversionRate: PromiseOrValue<BigNumberish>;
    referrer: PromiseOrValue<string>;
    referrerFee: PromiseOrValue<BigNumberish>;
    gatingServiceSignature: PromiseOrValue<BytesLike>;
    signatureExpiration: PromiseOrValue<BigNumberish>;
    postIntentHook: PromiseOrValue<string>;
    data: PromiseOrValue<BytesLike>;
  };

  export type SignalIntentParamsStructOutput = [
    string,
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    string,
    BigNumber,
    string,
    BigNumber,
    string,
    string
  ] & {
    escrow: string;
    depositId: BigNumber;
    amount: BigNumber;
    to: string;
    paymentMethod: string;
    fiatCurrency: string;
    conversionRate: BigNumber;
    referrer: string;
    referrerFee: BigNumber;
    gatingServiceSignature: string;
    signatureExpiration: BigNumber;
    postIntentHook: string;
    data: string;
  };
}

export interface OrchestratorInterface extends utils.Interface {
  functions: {
    "allowMultipleIntents()": FunctionFragment;
    "cancelIntent(bytes32)": FunctionFragment;
    "chainId()": FunctionFragment;
    "escrowRegistry()": FunctionFragment;
    "fulfillIntent((bytes,bytes32,bytes,bytes))": FunctionFragment;
    "getAccountIntents(address)": FunctionFragment;
    "getIntent(bytes32)": FunctionFragment;
    "getIntentMinAtSignal(bytes32)": FunctionFragment;
    "intentCounter()": FunctionFragment;
    "owner()": FunctionFragment;
    "pauseOrchestrator()": FunctionFragment;
    "paused()": FunctionFragment;
    "paymentVerifierRegistry()": FunctionFragment;
    "postIntentHookRegistry()": FunctionFragment;
    "protocolFee()": FunctionFragment;
    "protocolFeeRecipient()": FunctionFragment;
    "pruneIntents(bytes32[])": FunctionFragment;
    "relayerRegistry()": FunctionFragment;
    "releaseFundsToPayer(bytes32)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setAllowMultipleIntents(bool)": FunctionFragment;
    "setEscrowRegistry(address)": FunctionFragment;
    "setPostIntentHookRegistry(address)": FunctionFragment;
    "setProtocolFee(uint256)": FunctionFragment;
    "setProtocolFeeRecipient(address)": FunctionFragment;
    "setRelayerRegistry(address)": FunctionFragment;
    "signalIntent((address,uint256,uint256,address,bytes32,bytes32,uint256,address,uint256,bytes,uint256,address,bytes))": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "unpauseOrchestrator()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "allowMultipleIntents"
      | "cancelIntent"
      | "chainId"
      | "escrowRegistry"
      | "fulfillIntent"
      | "getAccountIntents"
      | "getIntent"
      | "getIntentMinAtSignal"
      | "intentCounter"
      | "owner"
      | "pauseOrchestrator"
      | "paused"
      | "paymentVerifierRegistry"
      | "postIntentHookRegistry"
      | "protocolFee"
      | "protocolFeeRecipient"
      | "pruneIntents"
      | "relayerRegistry"
      | "releaseFundsToPayer"
      | "renounceOwnership"
      | "setAllowMultipleIntents"
      | "setEscrowRegistry"
      | "setPostIntentHookRegistry"
      | "setProtocolFee"
      | "setProtocolFeeRecipient"
      | "setRelayerRegistry"
      | "signalIntent"
      | "transferOwnership"
      | "unpauseOrchestrator"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "allowMultipleIntents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelIntent",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "chainId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "escrowRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillIntent",
    values: [IOrchestrator.FulfillIntentParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountIntents",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntent",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getIntentMinAtSignal",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "intentCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauseOrchestrator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentVerifierRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "postIntentHookRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pruneIntents",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "relayerRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFundsToPayer",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowMultipleIntents",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrowRegistry",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPostIntentHookRegistry",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeeRecipient",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayerRegistry",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "signalIntent",
    values: [IOrchestrator.SignalIntentParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseOrchestrator",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "allowMultipleIntents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chainId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "escrowRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fulfillIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountIntents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getIntent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIntentMinAtSignal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "intentCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauseOrchestrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentVerifierRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "postIntentHookRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pruneIntents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayerRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFundsToPayer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowMultipleIntents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEscrowRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPostIntentHookRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRelayerRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signalIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseOrchestrator",
    data: BytesLike
  ): Result;

  events: {
    "AllowMultipleIntentsUpdated(bool)": EventFragment;
    "EscrowRegistryUpdated(address)": EventFragment;
    "IntentFulfilled(bytes32,address,uint256,bool)": EventFragment;
    "IntentPruned(bytes32)": EventFragment;
    "IntentSignaled(bytes32,address,uint256,bytes32,address,address,uint256,bytes32,uint256,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PartialManualReleaseDelayUpdated(uint256)": EventFragment;
    "Paused(address)": EventFragment;
    "PaymentVerifierRegistryUpdated(address)": EventFragment;
    "PostIntentHookRegistryUpdated(address)": EventFragment;
    "ProtocolFeeRecipientUpdated(address)": EventFragment;
    "ProtocolFeeUpdated(uint256)": EventFragment;
    "RelayerRegistryUpdated(address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "AllowMultipleIntentsUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EscrowRegistryUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "IntentFulfilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "IntentPruned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "IntentSignaled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "PartialManualReleaseDelayUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "PaymentVerifierRegistryUpdated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "PostIntentHookRegistryUpdated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "ProtocolFeeRecipientUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProtocolFeeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelayerRegistryUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export interface AllowMultipleIntentsUpdatedEventObject {
  allowMultiple: boolean;
}
export type AllowMultipleIntentsUpdatedEvent = TypedEvent<
  [boolean],
  AllowMultipleIntentsUpdatedEventObject
>;

export type AllowMultipleIntentsUpdatedEventFilter =
  TypedEventFilter<AllowMultipleIntentsUpdatedEvent>;

export interface EscrowRegistryUpdatedEventObject {
  escrowRegistry: string;
}
export type EscrowRegistryUpdatedEvent = TypedEvent<
  [string],
  EscrowRegistryUpdatedEventObject
>;

export type EscrowRegistryUpdatedEventFilter =
  TypedEventFilter<EscrowRegistryUpdatedEvent>;

export interface IntentFulfilledEventObject {
  intentHash: string;
  fundsTransferredTo: string;
  amount: BigNumber;
  isManualRelease: boolean;
}
export type IntentFulfilledEvent = TypedEvent<
  [string, string, BigNumber, boolean],
  IntentFulfilledEventObject
>;

export type IntentFulfilledEventFilter = TypedEventFilter<IntentFulfilledEvent>;

export interface IntentPrunedEventObject {
  intentHash: string;
}
export type IntentPrunedEvent = TypedEvent<[string], IntentPrunedEventObject>;

export type IntentPrunedEventFilter = TypedEventFilter<IntentPrunedEvent>;

export interface IntentSignaledEventObject {
  intentHash: string;
  escrow: string;
  depositId: BigNumber;
  paymentMethod: string;
  owner: string;
  to: string;
  amount: BigNumber;
  fiatCurrency: string;
  conversionRate: BigNumber;
  timestamp: BigNumber;
}
export type IntentSignaledEvent = TypedEvent<
  [
    string,
    string,
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    string,
    BigNumber,
    BigNumber
  ],
  IntentSignaledEventObject
>;

export type IntentSignaledEventFilter = TypedEventFilter<IntentSignaledEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PartialManualReleaseDelayUpdatedEventObject {
  partialManualReleaseDelay: BigNumber;
}
export type PartialManualReleaseDelayUpdatedEvent = TypedEvent<
  [BigNumber],
  PartialManualReleaseDelayUpdatedEventObject
>;

export type PartialManualReleaseDelayUpdatedEventFilter =
  TypedEventFilter<PartialManualReleaseDelayUpdatedEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface PaymentVerifierRegistryUpdatedEventObject {
  paymentVerifierRegistry: string;
}
export type PaymentVerifierRegistryUpdatedEvent = TypedEvent<
  [string],
  PaymentVerifierRegistryUpdatedEventObject
>;

export type PaymentVerifierRegistryUpdatedEventFilter =
  TypedEventFilter<PaymentVerifierRegistryUpdatedEvent>;

export interface PostIntentHookRegistryUpdatedEventObject {
  postIntentHookRegistry: string;
}
export type PostIntentHookRegistryUpdatedEvent = TypedEvent<
  [string],
  PostIntentHookRegistryUpdatedEventObject
>;

export type PostIntentHookRegistryUpdatedEventFilter =
  TypedEventFilter<PostIntentHookRegistryUpdatedEvent>;

export interface ProtocolFeeRecipientUpdatedEventObject {
  protocolFeeRecipient: string;
}
export type ProtocolFeeRecipientUpdatedEvent = TypedEvent<
  [string],
  ProtocolFeeRecipientUpdatedEventObject
>;

export type ProtocolFeeRecipientUpdatedEventFilter =
  TypedEventFilter<ProtocolFeeRecipientUpdatedEvent>;

export interface ProtocolFeeUpdatedEventObject {
  protocolFee: BigNumber;
}
export type ProtocolFeeUpdatedEvent = TypedEvent<
  [BigNumber],
  ProtocolFeeUpdatedEventObject
>;

export type ProtocolFeeUpdatedEventFilter =
  TypedEventFilter<ProtocolFeeUpdatedEvent>;

export interface RelayerRegistryUpdatedEventObject {
  relayerRegistry: string;
}
export type RelayerRegistryUpdatedEvent = TypedEvent<
  [string],
  RelayerRegistryUpdatedEventObject
>;

export type RelayerRegistryUpdatedEventFilter =
  TypedEventFilter<RelayerRegistryUpdatedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface Orchestrator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OrchestratorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    allowMultipleIntents(overrides?: CallOverrides): Promise<[boolean]>;

    cancelIntent(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    chainId(overrides?: CallOverrides): Promise<[BigNumber]>;

    escrowRegistry(overrides?: CallOverrides): Promise<[string]>;

    fulfillIntent(
      _params: IOrchestrator.FulfillIntentParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAccountIntents(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getIntent(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[IOrchestrator.IntentStructOutput]>;

    getIntentMinAtSignal(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    intentCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pauseOrchestrator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    paymentVerifierRegistry(overrides?: CallOverrides): Promise<[string]>;

    postIntentHookRegistry(overrides?: CallOverrides): Promise<[string]>;

    protocolFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<[string]>;

    pruneIntents(
      _intents: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    relayerRegistry(overrides?: CallOverrides): Promise<[string]>;

    releaseFundsToPayer(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAllowMultipleIntents(
      _allowMultiple: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setEscrowRegistry(
      _escrowRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPostIntentHookRegistry(
      _postIntentHookRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setProtocolFee(
      _protocolFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setProtocolFeeRecipient(
      _protocolFeeRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRelayerRegistry(
      _relayerRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    signalIntent(
      _params: IOrchestrator.SignalIntentParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpauseOrchestrator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  allowMultipleIntents(overrides?: CallOverrides): Promise<boolean>;

  cancelIntent(
    _intentHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  chainId(overrides?: CallOverrides): Promise<BigNumber>;

  escrowRegistry(overrides?: CallOverrides): Promise<string>;

  fulfillIntent(
    _params: IOrchestrator.FulfillIntentParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAccountIntents(
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getIntent(
    _intentHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<IOrchestrator.IntentStructOutput>;

  getIntentMinAtSignal(
    _intentHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  intentCounter(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  pauseOrchestrator(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  paymentVerifierRegistry(overrides?: CallOverrides): Promise<string>;

  postIntentHookRegistry(overrides?: CallOverrides): Promise<string>;

  protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

  protocolFeeRecipient(overrides?: CallOverrides): Promise<string>;

  pruneIntents(
    _intents: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  relayerRegistry(overrides?: CallOverrides): Promise<string>;

  releaseFundsToPayer(
    _intentHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAllowMultipleIntents(
    _allowMultiple: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setEscrowRegistry(
    _escrowRegistry: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPostIntentHookRegistry(
    _postIntentHookRegistry: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setProtocolFee(
    _protocolFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setProtocolFeeRecipient(
    _protocolFeeRecipient: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRelayerRegistry(
    _relayerRegistry: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  signalIntent(
    _params: IOrchestrator.SignalIntentParamsStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpauseOrchestrator(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    allowMultipleIntents(overrides?: CallOverrides): Promise<boolean>;

    cancelIntent(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    chainId(overrides?: CallOverrides): Promise<BigNumber>;

    escrowRegistry(overrides?: CallOverrides): Promise<string>;

    fulfillIntent(
      _params: IOrchestrator.FulfillIntentParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    getAccountIntents(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getIntent(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<IOrchestrator.IntentStructOutput>;

    getIntentMinAtSignal(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    intentCounter(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    pauseOrchestrator(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    paymentVerifierRegistry(overrides?: CallOverrides): Promise<string>;

    postIntentHookRegistry(overrides?: CallOverrides): Promise<string>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<string>;

    pruneIntents(
      _intents: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    relayerRegistry(overrides?: CallOverrides): Promise<string>;

    releaseFundsToPayer(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setAllowMultipleIntents(
      _allowMultiple: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setEscrowRegistry(
      _escrowRegistry: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPostIntentHookRegistry(
      _postIntentHookRegistry: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFee(
      _protocolFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFeeRecipient(
      _protocolFeeRecipient: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRelayerRegistry(
      _relayerRegistry: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    signalIntent(
      _params: IOrchestrator.SignalIntentParamsStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpauseOrchestrator(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AllowMultipleIntentsUpdated(bool)"(
      allowMultiple?: null
    ): AllowMultipleIntentsUpdatedEventFilter;
    AllowMultipleIntentsUpdated(
      allowMultiple?: null
    ): AllowMultipleIntentsUpdatedEventFilter;

    "EscrowRegistryUpdated(address)"(
      escrowRegistry?: PromiseOrValue<string> | null
    ): EscrowRegistryUpdatedEventFilter;
    EscrowRegistryUpdated(
      escrowRegistry?: PromiseOrValue<string> | null
    ): EscrowRegistryUpdatedEventFilter;

    "IntentFulfilled(bytes32,address,uint256,bool)"(
      intentHash?: PromiseOrValue<BytesLike> | null,
      fundsTransferredTo?: PromiseOrValue<string> | null,
      amount?: null,
      isManualRelease?: null
    ): IntentFulfilledEventFilter;
    IntentFulfilled(
      intentHash?: PromiseOrValue<BytesLike> | null,
      fundsTransferredTo?: PromiseOrValue<string> | null,
      amount?: null,
      isManualRelease?: null
    ): IntentFulfilledEventFilter;

    "IntentPruned(bytes32)"(
      intentHash?: PromiseOrValue<BytesLike> | null
    ): IntentPrunedEventFilter;
    IntentPruned(
      intentHash?: PromiseOrValue<BytesLike> | null
    ): IntentPrunedEventFilter;

    "IntentSignaled(bytes32,address,uint256,bytes32,address,address,uint256,bytes32,uint256,uint256)"(
      intentHash?: PromiseOrValue<BytesLike> | null,
      escrow?: PromiseOrValue<string> | null,
      depositId?: PromiseOrValue<BigNumberish> | null,
      paymentMethod?: null,
      owner?: null,
      to?: null,
      amount?: null,
      fiatCurrency?: null,
      conversionRate?: null,
      timestamp?: null
    ): IntentSignaledEventFilter;
    IntentSignaled(
      intentHash?: PromiseOrValue<BytesLike> | null,
      escrow?: PromiseOrValue<string> | null,
      depositId?: PromiseOrValue<BigNumberish> | null,
      paymentMethod?: null,
      owner?: null,
      to?: null,
      amount?: null,
      fiatCurrency?: null,
      conversionRate?: null,
      timestamp?: null
    ): IntentSignaledEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "PartialManualReleaseDelayUpdated(uint256)"(
      partialManualReleaseDelay?: null
    ): PartialManualReleaseDelayUpdatedEventFilter;
    PartialManualReleaseDelayUpdated(
      partialManualReleaseDelay?: null
    ): PartialManualReleaseDelayUpdatedEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "PaymentVerifierRegistryUpdated(address)"(
      paymentVerifierRegistry?: PromiseOrValue<string> | null
    ): PaymentVerifierRegistryUpdatedEventFilter;
    PaymentVerifierRegistryUpdated(
      paymentVerifierRegistry?: PromiseOrValue<string> | null
    ): PaymentVerifierRegistryUpdatedEventFilter;

    "PostIntentHookRegistryUpdated(address)"(
      postIntentHookRegistry?: PromiseOrValue<string> | null
    ): PostIntentHookRegistryUpdatedEventFilter;
    PostIntentHookRegistryUpdated(
      postIntentHookRegistry?: PromiseOrValue<string> | null
    ): PostIntentHookRegistryUpdatedEventFilter;

    "ProtocolFeeRecipientUpdated(address)"(
      protocolFeeRecipient?: PromiseOrValue<string> | null
    ): ProtocolFeeRecipientUpdatedEventFilter;
    ProtocolFeeRecipientUpdated(
      protocolFeeRecipient?: PromiseOrValue<string> | null
    ): ProtocolFeeRecipientUpdatedEventFilter;

    "ProtocolFeeUpdated(uint256)"(
      protocolFee?: null
    ): ProtocolFeeUpdatedEventFilter;
    ProtocolFeeUpdated(protocolFee?: null): ProtocolFeeUpdatedEventFilter;

    "RelayerRegistryUpdated(address)"(
      relayerRegistry?: PromiseOrValue<string> | null
    ): RelayerRegistryUpdatedEventFilter;
    RelayerRegistryUpdated(
      relayerRegistry?: PromiseOrValue<string> | null
    ): RelayerRegistryUpdatedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;
  };

  estimateGas: {
    allowMultipleIntents(overrides?: CallOverrides): Promise<BigNumber>;

    cancelIntent(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    chainId(overrides?: CallOverrides): Promise<BigNumber>;

    escrowRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    fulfillIntent(
      _params: IOrchestrator.FulfillIntentParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAccountIntents(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIntent(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getIntentMinAtSignal(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    intentCounter(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pauseOrchestrator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    paymentVerifierRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    postIntentHookRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeRecipient(overrides?: CallOverrides): Promise<BigNumber>;

    pruneIntents(
      _intents: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    relayerRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    releaseFundsToPayer(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAllowMultipleIntents(
      _allowMultiple: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setEscrowRegistry(
      _escrowRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPostIntentHookRegistry(
      _postIntentHookRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setProtocolFee(
      _protocolFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setProtocolFeeRecipient(
      _protocolFeeRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRelayerRegistry(
      _relayerRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    signalIntent(
      _params: IOrchestrator.SignalIntentParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpauseOrchestrator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    allowMultipleIntents(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelIntent(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    chainId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    escrowRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fulfillIntent(
      _params: IOrchestrator.FulfillIntentParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAccountIntents(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIntent(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIntentMinAtSignal(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    intentCounter(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pauseOrchestrator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paymentVerifierRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    postIntentHookRegistry(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    protocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeRecipient(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pruneIntents(
      _intents: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    relayerRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    releaseFundsToPayer(
      _intentHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAllowMultipleIntents(
      _allowMultiple: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setEscrowRegistry(
      _escrowRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPostIntentHookRegistry(
      _postIntentHookRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolFee(
      _protocolFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolFeeRecipient(
      _protocolFeeRecipient: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRelayerRegistry(
      _relayerRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    signalIntent(
      _params: IOrchestrator.SignalIntentParamsStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpauseOrchestrator(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
