/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace RateManagerV1 {
  export type RateManagerConfigStruct = {
    manager: PromiseOrValue<string>;
    feeRecipient: PromiseOrValue<string>;
    maxFee: PromiseOrValue<BigNumberish>;
    fee: PromiseOrValue<BigNumberish>;
    minLiquidity: PromiseOrValue<BigNumberish>;
    name: PromiseOrValue<string>;
    uri: PromiseOrValue<string>;
  };

  export type RateManagerConfigStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string
  ] & {
    manager: string;
    feeRecipient: string;
    maxFee: BigNumber;
    fee: BigNumber;
    minLiquidity: BigNumber;
    name: string;
    uri: string;
  };

  export type DepositorFloorConfigStruct = {
    enabled: PromiseOrValue<boolean>;
    floorFixed: PromiseOrValue<BigNumberish>;
    floorSpreadBps: PromiseOrValue<BigNumberish>;
    oracleAdapter: PromiseOrValue<string>;
    adapterConfig: PromiseOrValue<BytesLike>;
    maxStaleness: PromiseOrValue<BigNumberish>;
  };

  export type DepositorFloorConfigStructOutput = [
    boolean,
    BigNumber,
    number,
    string,
    string,
    number
  ] & {
    enabled: boolean;
    floorFixed: BigNumber;
    floorSpreadBps: number;
    oracleAdapter: string;
    adapterConfig: string;
    maxStaleness: number;
  };
}

export interface RateManagerV1Interface extends utils.Interface {
  functions: {
    "GLOBAL_MAX_MANAGER_FEE()": FunctionFragment;
    "createRateManager((address,address,uint256,uint256,uint256,string,string))": FunctionFragment;
    "escrowRegistry()": FunctionFragment;
    "getDepositorFloor(bytes32,address,uint256,bytes32,bytes32)": FunctionFragment;
    "getFee(bytes32)": FunctionFragment;
    "getManagerRate(bytes32,bytes32,bytes32)": FunctionFragment;
    "getRate(bytes32,address,uint256,bytes32,bytes32)": FunctionFragment;
    "getRateManager(bytes32)": FunctionFragment;
    "isDepositorCurrencyEnabled(bytes32,address,uint256,bytes32,bytes32)": FunctionFragment;
    "isRateManager(bytes32)": FunctionFragment;
    "onDepositOptIn(uint256,bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setDepositorCurrencyEnabled(bytes32,address,uint256,bytes32,bytes32,bool)": FunctionFragment;
    "setDepositorCurrencyEnabledBatch(bytes32,address,uint256,bytes32[],bytes32[][],bool[][])": FunctionFragment;
    "setDepositorFloor(bytes32,address,uint256,bytes32,bytes32,(bool,uint256,uint16,address,bytes,uint32))": FunctionFragment;
    "setDepositorFloorBatch(bytes32,address,uint256,bytes32[],bytes32[][],tuple[][])": FunctionFragment;
    "setEscrowRegistry(address)": FunctionFragment;
    "setFee(bytes32,uint256)": FunctionFragment;
    "setMinLiquidity(bytes32,uint256)": FunctionFragment;
    "setRate(bytes32,bytes32,bytes32,uint256)": FunctionFragment;
    "setRateBatch(bytes32,bytes32[],bytes32[][],uint256[][])": FunctionFragment;
    "setRateManagerConfig(bytes32,address,address,string,string)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "GLOBAL_MAX_MANAGER_FEE"
      | "createRateManager"
      | "escrowRegistry"
      | "getDepositorFloor"
      | "getFee"
      | "getManagerRate"
      | "getRate"
      | "getRateManager"
      | "isDepositorCurrencyEnabled"
      | "isRateManager"
      | "onDepositOptIn"
      | "owner"
      | "renounceOwnership"
      | "setDepositorCurrencyEnabled"
      | "setDepositorCurrencyEnabledBatch"
      | "setDepositorFloor"
      | "setDepositorFloorBatch"
      | "setEscrowRegistry"
      | "setFee"
      | "setMinLiquidity"
      | "setRate"
      | "setRateBatch"
      | "setRateManagerConfig"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "GLOBAL_MAX_MANAGER_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createRateManager",
    values: [RateManagerV1.RateManagerConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositorFloor",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getFee",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getManagerRate",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getRate",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getRateManager",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "isDepositorCurrencyEnabled",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isRateManager",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "onDepositOptIn",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositorCurrencyEnabled",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositorCurrencyEnabledBatch",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[][],
      PromiseOrValue<boolean>[][]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositorFloor",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      RateManagerV1.DepositorFloorConfigStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositorFloorBatch",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[][],
      RateManagerV1.DepositorFloorConfigStruct[][]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setEscrowRegistry",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinLiquidity",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRate",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setRateBatch",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<BytesLike>[][],
      PromiseOrValue<BigNumberish>[][]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setRateManagerConfig",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "GLOBAL_MAX_MANAGER_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRateManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositorFloor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getManagerRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRateManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDepositorCurrencyEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRateManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onDepositOptIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositorCurrencyEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositorCurrencyEnabledBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositorFloor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositorFloorBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEscrowRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRateBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRateManagerConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "DepositorCurrencyEnabledSet(bytes32,address,uint256,bytes32,bytes32,bool)": EventFragment;
    "DepositorFloorSet(bytes32,address,uint256,bytes32,bytes32,uint256,uint16,address,bytes,uint32,bool)": EventFragment;
    "EscrowRegistryUpdated(address)": EventFragment;
    "MinLiquidityUpdated(bytes32,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "RateManagerConfigUpdated(bytes32,address,address,string,string)": EventFragment;
    "RateManagerCreated(bytes32,address,address,uint256,uint256,string,string)": EventFragment;
    "RateManagerFeeUpdated(bytes32,uint256)": EventFragment;
    "RateManagerRateUpdated(bytes32,bytes32,bytes32,uint256)": EventFragment;
    "RateManagerRatesBatchUpdated(bytes32,uint256)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "DepositorCurrencyEnabledSet"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DepositorFloorSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EscrowRegistryUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MinLiquidityUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RateManagerConfigUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RateManagerCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RateManagerFeeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RateManagerRateUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "RateManagerRatesBatchUpdated"
  ): EventFragment;
}

export interface DepositorCurrencyEnabledSetEventObject {
  rateManagerId: string;
  escrow: string;
  depositId: BigNumber;
  paymentMethod: string;
  currencyCode: string;
  enabled: boolean;
}
export type DepositorCurrencyEnabledSetEvent = TypedEvent<
  [string, string, BigNumber, string, string, boolean],
  DepositorCurrencyEnabledSetEventObject
>;

export type DepositorCurrencyEnabledSetEventFilter =
  TypedEventFilter<DepositorCurrencyEnabledSetEvent>;

export interface DepositorFloorSetEventObject {
  rateManagerId: string;
  escrow: string;
  depositId: BigNumber;
  paymentMethod: string;
  currencyCode: string;
  floorFixed: BigNumber;
  floorSpreadBps: number;
  oracleAdapter: string;
  adapterConfig: string;
  maxStaleness: number;
  enabled: boolean;
}
export type DepositorFloorSetEvent = TypedEvent<
  [
    string,
    string,
    BigNumber,
    string,
    string,
    BigNumber,
    number,
    string,
    string,
    number,
    boolean
  ],
  DepositorFloorSetEventObject
>;

export type DepositorFloorSetEventFilter =
  TypedEventFilter<DepositorFloorSetEvent>;

export interface EscrowRegistryUpdatedEventObject {
  escrowRegistry: string;
}
export type EscrowRegistryUpdatedEvent = TypedEvent<
  [string],
  EscrowRegistryUpdatedEventObject
>;

export type EscrowRegistryUpdatedEventFilter =
  TypedEventFilter<EscrowRegistryUpdatedEvent>;

export interface MinLiquidityUpdatedEventObject {
  rateManagerId: string;
  minLiquidity: BigNumber;
}
export type MinLiquidityUpdatedEvent = TypedEvent<
  [string, BigNumber],
  MinLiquidityUpdatedEventObject
>;

export type MinLiquidityUpdatedEventFilter =
  TypedEventFilter<MinLiquidityUpdatedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface RateManagerConfigUpdatedEventObject {
  rateManagerId: string;
  manager: string;
  feeRecipient: string;
  name: string;
  uri: string;
}
export type RateManagerConfigUpdatedEvent = TypedEvent<
  [string, string, string, string, string],
  RateManagerConfigUpdatedEventObject
>;

export type RateManagerConfigUpdatedEventFilter =
  TypedEventFilter<RateManagerConfigUpdatedEvent>;

export interface RateManagerCreatedEventObject {
  rateManagerId: string;
  manager: string;
  feeRecipient: string;
  maxFee: BigNumber;
  fee: BigNumber;
  name: string;
  uri: string;
}
export type RateManagerCreatedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber, string, string],
  RateManagerCreatedEventObject
>;

export type RateManagerCreatedEventFilter =
  TypedEventFilter<RateManagerCreatedEvent>;

export interface RateManagerFeeUpdatedEventObject {
  rateManagerId: string;
  fee: BigNumber;
}
export type RateManagerFeeUpdatedEvent = TypedEvent<
  [string, BigNumber],
  RateManagerFeeUpdatedEventObject
>;

export type RateManagerFeeUpdatedEventFilter =
  TypedEventFilter<RateManagerFeeUpdatedEvent>;

export interface RateManagerRateUpdatedEventObject {
  rateManagerId: string;
  paymentMethod: string;
  currencyCode: string;
  rate: BigNumber;
}
export type RateManagerRateUpdatedEvent = TypedEvent<
  [string, string, string, BigNumber],
  RateManagerRateUpdatedEventObject
>;

export type RateManagerRateUpdatedEventFilter =
  TypedEventFilter<RateManagerRateUpdatedEvent>;

export interface RateManagerRatesBatchUpdatedEventObject {
  rateManagerId: string;
  totalUpdated: BigNumber;
}
export type RateManagerRatesBatchUpdatedEvent = TypedEvent<
  [string, BigNumber],
  RateManagerRatesBatchUpdatedEventObject
>;

export type RateManagerRatesBatchUpdatedEventFilter =
  TypedEventFilter<RateManagerRatesBatchUpdatedEvent>;

export interface RateManagerV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RateManagerV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    GLOBAL_MAX_MANAGER_FEE(overrides?: CallOverrides): Promise<[BigNumber]>;

    createRateManager(
      _config: RateManagerV1.RateManagerConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    escrowRegistry(overrides?: CallOverrides): Promise<[string]>;

    getDepositorFloor(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [RateManagerV1.DepositorFloorConfigStructOutput] & {
        config: RateManagerV1.DepositorFloorConfigStructOutput;
      }
    >;

    getFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { recipient: string; fee: BigNumber }>;

    getManagerRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rate: BigNumber }>;

    getRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rate: BigNumber }>;

    getRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [RateManagerV1.RateManagerConfigStructOutput] & {
        config: RateManagerV1.RateManagerConfigStructOutput;
      }
    >;

    isDepositorCurrencyEnabled(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { enabled: boolean }>;

    isRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { exists: boolean }>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[void]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDepositorCurrencyEnabled(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDepositorCurrencyEnabledBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _enabled: PromiseOrValue<boolean>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDepositorFloor(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _config: RateManagerV1.DepositorFloorConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDepositorFloorBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _configs: RateManagerV1.DepositorFloorConfigStruct[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setEscrowRegistry(
      _escrowRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setMinLiquidity(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _minLiquidity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _rate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRateBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _rates: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRateManagerConfig(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _manager: PromiseOrValue<string>,
      _feeRecipient: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  GLOBAL_MAX_MANAGER_FEE(overrides?: CallOverrides): Promise<BigNumber>;

  createRateManager(
    _config: RateManagerV1.RateManagerConfigStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  escrowRegistry(overrides?: CallOverrides): Promise<string>;

  getDepositorFloor(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _escrow: PromiseOrValue<string>,
    _depositId: PromiseOrValue<BigNumberish>,
    _paymentMethod: PromiseOrValue<BytesLike>,
    _currencyCode: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<RateManagerV1.DepositorFloorConfigStructOutput>;

  getFee(
    _rateManagerId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { recipient: string; fee: BigNumber }>;

  getManagerRate(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _paymentMethod: PromiseOrValue<BytesLike>,
    _currencyCode: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRate(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _escrow: PromiseOrValue<string>,
    _depositId: PromiseOrValue<BigNumberish>,
    _paymentMethod: PromiseOrValue<BytesLike>,
    _currencyCode: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRateManager(
    _rateManagerId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<RateManagerV1.RateManagerConfigStructOutput>;

  isDepositorCurrencyEnabled(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _escrow: PromiseOrValue<string>,
    _depositId: PromiseOrValue<BigNumberish>,
    _paymentMethod: PromiseOrValue<BytesLike>,
    _currencyCode: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isRateManager(
    _rateManagerId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  onDepositOptIn(
    _depositId: PromiseOrValue<BigNumberish>,
    _rateManagerId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<void>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDepositorCurrencyEnabled(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _escrow: PromiseOrValue<string>,
    _depositId: PromiseOrValue<BigNumberish>,
    _paymentMethod: PromiseOrValue<BytesLike>,
    _currencyCode: PromiseOrValue<BytesLike>,
    _enabled: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDepositorCurrencyEnabledBatch(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _escrow: PromiseOrValue<string>,
    _depositId: PromiseOrValue<BigNumberish>,
    _paymentMethods: PromiseOrValue<BytesLike>[],
    _currencyCodes: PromiseOrValue<BytesLike>[][],
    _enabled: PromiseOrValue<boolean>[][],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDepositorFloor(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _escrow: PromiseOrValue<string>,
    _depositId: PromiseOrValue<BigNumberish>,
    _paymentMethod: PromiseOrValue<BytesLike>,
    _currencyCode: PromiseOrValue<BytesLike>,
    _config: RateManagerV1.DepositorFloorConfigStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDepositorFloorBatch(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _escrow: PromiseOrValue<string>,
    _depositId: PromiseOrValue<BigNumberish>,
    _paymentMethods: PromiseOrValue<BytesLike>[],
    _currencyCodes: PromiseOrValue<BytesLike>[][],
    _configs: RateManagerV1.DepositorFloorConfigStruct[][],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setEscrowRegistry(
    _escrowRegistry: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFee(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _fee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setMinLiquidity(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _minLiquidity: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRate(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _paymentMethod: PromiseOrValue<BytesLike>,
    _currencyCode: PromiseOrValue<BytesLike>,
    _rate: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRateBatch(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _paymentMethods: PromiseOrValue<BytesLike>[],
    _currencyCodes: PromiseOrValue<BytesLike>[][],
    _rates: PromiseOrValue<BigNumberish>[][],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRateManagerConfig(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _manager: PromiseOrValue<string>,
    _feeRecipient: PromiseOrValue<string>,
    _name: PromiseOrValue<string>,
    _uri: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    GLOBAL_MAX_MANAGER_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    createRateManager(
      _config: RateManagerV1.RateManagerConfigStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    escrowRegistry(overrides?: CallOverrides): Promise<string>;

    getDepositorFloor(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<RateManagerV1.DepositorFloorConfigStructOutput>;

    getFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { recipient: string; fee: BigNumber }>;

    getManagerRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<RateManagerV1.RateManagerConfigStructOutput>;

    isDepositorCurrencyEnabled(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setDepositorCurrencyEnabled(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _enabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDepositorCurrencyEnabledBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _enabled: PromiseOrValue<boolean>[][],
      overrides?: CallOverrides
    ): Promise<void>;

    setDepositorFloor(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _config: RateManagerV1.DepositorFloorConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setDepositorFloorBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _configs: RateManagerV1.DepositorFloorConfigStruct[][],
      overrides?: CallOverrides
    ): Promise<void>;

    setEscrowRegistry(
      _escrowRegistry: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setMinLiquidity(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _minLiquidity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _rate: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRateBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _rates: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<void>;

    setRateManagerConfig(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _manager: PromiseOrValue<string>,
      _feeRecipient: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _uri: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DepositorCurrencyEnabledSet(bytes32,address,uint256,bytes32,bytes32,bool)"(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      escrow?: PromiseOrValue<string> | null,
      depositId?: PromiseOrValue<BigNumberish> | null,
      paymentMethod?: null,
      currencyCode?: null,
      enabled?: null
    ): DepositorCurrencyEnabledSetEventFilter;
    DepositorCurrencyEnabledSet(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      escrow?: PromiseOrValue<string> | null,
      depositId?: PromiseOrValue<BigNumberish> | null,
      paymentMethod?: null,
      currencyCode?: null,
      enabled?: null
    ): DepositorCurrencyEnabledSetEventFilter;

    "DepositorFloorSet(bytes32,address,uint256,bytes32,bytes32,uint256,uint16,address,bytes,uint32,bool)"(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      escrow?: PromiseOrValue<string> | null,
      depositId?: PromiseOrValue<BigNumberish> | null,
      paymentMethod?: null,
      currencyCode?: null,
      floorFixed?: null,
      floorSpreadBps?: null,
      oracleAdapter?: null,
      adapterConfig?: null,
      maxStaleness?: null,
      enabled?: null
    ): DepositorFloorSetEventFilter;
    DepositorFloorSet(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      escrow?: PromiseOrValue<string> | null,
      depositId?: PromiseOrValue<BigNumberish> | null,
      paymentMethod?: null,
      currencyCode?: null,
      floorFixed?: null,
      floorSpreadBps?: null,
      oracleAdapter?: null,
      adapterConfig?: null,
      maxStaleness?: null,
      enabled?: null
    ): DepositorFloorSetEventFilter;

    "EscrowRegistryUpdated(address)"(
      escrowRegistry?: PromiseOrValue<string> | null
    ): EscrowRegistryUpdatedEventFilter;
    EscrowRegistryUpdated(
      escrowRegistry?: PromiseOrValue<string> | null
    ): EscrowRegistryUpdatedEventFilter;

    "MinLiquidityUpdated(bytes32,uint256)"(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      minLiquidity?: null
    ): MinLiquidityUpdatedEventFilter;
    MinLiquidityUpdated(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      minLiquidity?: null
    ): MinLiquidityUpdatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "RateManagerConfigUpdated(bytes32,address,address,string,string)"(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      manager?: PromiseOrValue<string> | null,
      feeRecipient?: PromiseOrValue<string> | null,
      name?: null,
      uri?: null
    ): RateManagerConfigUpdatedEventFilter;
    RateManagerConfigUpdated(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      manager?: PromiseOrValue<string> | null,
      feeRecipient?: PromiseOrValue<string> | null,
      name?: null,
      uri?: null
    ): RateManagerConfigUpdatedEventFilter;

    "RateManagerCreated(bytes32,address,address,uint256,uint256,string,string)"(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      manager?: PromiseOrValue<string> | null,
      feeRecipient?: PromiseOrValue<string> | null,
      maxFee?: null,
      fee?: null,
      name?: null,
      uri?: null
    ): RateManagerCreatedEventFilter;
    RateManagerCreated(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      manager?: PromiseOrValue<string> | null,
      feeRecipient?: PromiseOrValue<string> | null,
      maxFee?: null,
      fee?: null,
      name?: null,
      uri?: null
    ): RateManagerCreatedEventFilter;

    "RateManagerFeeUpdated(bytes32,uint256)"(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      fee?: null
    ): RateManagerFeeUpdatedEventFilter;
    RateManagerFeeUpdated(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      fee?: null
    ): RateManagerFeeUpdatedEventFilter;

    "RateManagerRateUpdated(bytes32,bytes32,bytes32,uint256)"(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      paymentMethod?: PromiseOrValue<BytesLike> | null,
      currencyCode?: PromiseOrValue<BytesLike> | null,
      rate?: null
    ): RateManagerRateUpdatedEventFilter;
    RateManagerRateUpdated(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      paymentMethod?: PromiseOrValue<BytesLike> | null,
      currencyCode?: PromiseOrValue<BytesLike> | null,
      rate?: null
    ): RateManagerRateUpdatedEventFilter;

    "RateManagerRatesBatchUpdated(bytes32,uint256)"(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      totalUpdated?: null
    ): RateManagerRatesBatchUpdatedEventFilter;
    RateManagerRatesBatchUpdated(
      rateManagerId?: PromiseOrValue<BytesLike> | null,
      totalUpdated?: null
    ): RateManagerRatesBatchUpdatedEventFilter;
  };

  estimateGas: {
    GLOBAL_MAX_MANAGER_FEE(overrides?: CallOverrides): Promise<BigNumber>;

    createRateManager(
      _config: RateManagerV1.RateManagerConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    escrowRegistry(overrides?: CallOverrides): Promise<BigNumber>;

    getDepositorFloor(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getManagerRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isDepositorCurrencyEnabled(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDepositorCurrencyEnabled(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDepositorCurrencyEnabledBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _enabled: PromiseOrValue<boolean>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDepositorFloor(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _config: RateManagerV1.DepositorFloorConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDepositorFloorBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _configs: RateManagerV1.DepositorFloorConfigStruct[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setEscrowRegistry(
      _escrowRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setMinLiquidity(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _minLiquidity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _rate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRateBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _rates: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRateManagerConfig(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _manager: PromiseOrValue<string>,
      _feeRecipient: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    GLOBAL_MAX_MANAGER_FEE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createRateManager(
      _config: RateManagerV1.RateManagerConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    escrowRegistry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getDepositorFloor(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getManagerRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isDepositorCurrencyEnabled(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDepositorCurrencyEnabled(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _enabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDepositorCurrencyEnabledBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _enabled: PromiseOrValue<boolean>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDepositorFloor(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _config: RateManagerV1.DepositorFloorConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDepositorFloorBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _configs: RateManagerV1.DepositorFloorConfigStruct[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setEscrowRegistry(
      _escrowRegistry: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _fee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setMinLiquidity(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _minLiquidity: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      _rate: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRateBatch(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _paymentMethods: PromiseOrValue<BytesLike>[],
      _currencyCodes: PromiseOrValue<BytesLike>[][],
      _rates: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRateManagerConfig(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _manager: PromiseOrValue<string>,
      _feeRecipient: PromiseOrValue<string>,
      _name: PromiseOrValue<string>,
      _uri: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
