name = "xramp-orchestrator"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
PRIVY_APP_ID = "cmkcshfa402kxi20ce4puhb3t"
ADMIN_EMAILS = "rishmanx@gmail.com"
ADMIN_WALLET_ADDRESSES = ""
FUJI_RPC_URL = "https://api.avax-test.network/ext/bc/C/rpc"
ESCROW_CONTRACT_ADDRESS = "0xe1189d9644Ba8546FB421c02fd28bf64CF74F821"
MOCK_USDC_ADDRESS = "0xb2F4Ca689C54bCe4effcf8A12Cb02089C933C5c6"

# Secrets (set via `wrangler secret put`):
# PRIVY_APP_SECRET
# ARBITER_PRIVATE_KEY

[[d1_databases]]
binding = "DB"
database_name = "xramp-orchestrator-db"
database_id = "0b1edf49-e99b-43c2-9fe3-9d983bbdcffa"
