/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IOrchestrator {
  export type IntentStruct = {
    owner: PromiseOrValue<string>;
    to: PromiseOrValue<string>;
    escrow: PromiseOrValue<string>;
    depositId: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    timestamp: PromiseOrValue<BigNumberish>;
    paymentMethod: PromiseOrValue<BytesLike>;
    fiatCurrency: PromiseOrValue<BytesLike>;
    conversionRate: PromiseOrValue<BigNumberish>;
    payeeId: PromiseOrValue<BytesLike>;
    referrer: PromiseOrValue<string>;
    referrerFee: PromiseOrValue<BigNumberish>;
    postIntentHook: PromiseOrValue<string>;
    data: PromiseOrValue<BytesLike>;
  };

  export type IntentStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    string
  ] & {
    owner: string;
    to: string;
    escrow: string;
    depositId: BigNumber;
    amount: BigNumber;
    timestamp: BigNumber;
    paymentMethod: string;
    fiatCurrency: string;
    conversionRate: BigNumber;
    payeeId: string;
    referrer: string;
    referrerFee: BigNumber;
    postIntentHook: string;
    data: string;
  };
}

export interface PostIntentHookMockInterface extends utils.Interface {
  functions: {
    "execute((address,address,address,uint256,uint256,uint256,bytes32,bytes32,uint256,bytes32,address,uint256,address,bytes),uint256,bytes)": FunctionFragment;
    "orchestrator()": FunctionFragment;
    "usdc()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "execute" | "orchestrator" | "usdc"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [
      IOrchestrator.IntentStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "orchestrator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "orchestrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;

  events: {};
}

export interface PostIntentHookMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PostIntentHookMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    execute(
      _intent: IOrchestrator.IntentStruct,
      _amountNetFees: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    orchestrator(overrides?: CallOverrides): Promise<[string]>;

    usdc(overrides?: CallOverrides): Promise<[string]>;
  };

  execute(
    _intent: IOrchestrator.IntentStruct,
    _amountNetFees: PromiseOrValue<BigNumberish>,
    arg2: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  orchestrator(overrides?: CallOverrides): Promise<string>;

  usdc(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    execute(
      _intent: IOrchestrator.IntentStruct,
      _amountNetFees: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    orchestrator(overrides?: CallOverrides): Promise<string>;

    usdc(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    execute(
      _intent: IOrchestrator.IntentStruct,
      _amountNetFees: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    orchestrator(overrides?: CallOverrides): Promise<BigNumber>;

    usdc(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    execute(
      _intent: IOrchestrator.IntentStruct,
      _amountNetFees: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    orchestrator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    usdc(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
