/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IOrchestrator {
  export type IntentStruct = {
    owner: PromiseOrValue<string>;
    to: PromiseOrValue<string>;
    escrow: PromiseOrValue<string>;
    depositId: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    timestamp: PromiseOrValue<BigNumberish>;
    paymentMethod: PromiseOrValue<BytesLike>;
    fiatCurrency: PromiseOrValue<BytesLike>;
    conversionRate: PromiseOrValue<BigNumberish>;
    payeeId: PromiseOrValue<BytesLike>;
    referrer: PromiseOrValue<string>;
    referrerFee: PromiseOrValue<BigNumberish>;
    postIntentHook: PromiseOrValue<string>;
    data: PromiseOrValue<BytesLike>;
  };

  export type IntentStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    string
  ] & {
    owner: string;
    to: string;
    escrow: string;
    depositId: BigNumber;
    amount: BigNumber;
    timestamp: BigNumber;
    paymentMethod: string;
    fiatCurrency: string;
    conversionRate: BigNumber;
    payeeId: string;
    referrer: string;
    referrerFee: BigNumber;
    postIntentHook: string;
    data: string;
  };
}

export interface ReentrantPostIntentHookInterface extends utils.Interface {
  functions: {
    "attemptReentry()": FunctionFragment;
    "execute((address,address,address,uint256,uint256,uint256,bytes32,bytes32,uint256,bytes32,address,uint256,address,bytes),uint256,bytes)": FunctionFragment;
    "getReentrancyAttempts()": FunctionFragment;
    "orchestrator()": FunctionFragment;
    "reentrancyAttempts()": FunctionFragment;
    "setAttemptReentry(bool)": FunctionFragment;
    "setFulfillParams(bytes,bytes32,bytes,bytes)": FunctionFragment;
    "storedFulfillParams()": FunctionFragment;
    "usdc()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "attemptReentry"
      | "execute"
      | "getReentrancyAttempts"
      | "orchestrator"
      | "reentrancyAttempts"
      | "setAttemptReentry"
      | "setFulfillParams"
      | "storedFulfillParams"
      | "usdc"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "attemptReentry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [
      IOrchestrator.IntentStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getReentrancyAttempts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orchestrator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reentrancyAttempts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAttemptReentry",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFulfillParams",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "storedFulfillParams",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "attemptReentry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReentrancyAttempts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "orchestrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reentrancyAttempts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttemptReentry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFulfillParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storedFulfillParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;

  events: {
    "ExecutionCompleted(address,uint256)": EventFragment;
    "ReentrancyAttempted(bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ExecutionCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ReentrancyAttempted"): EventFragment;
}

export interface ExecutionCompletedEventObject {
  recipient: string;
  amount: BigNumber;
}
export type ExecutionCompletedEvent = TypedEvent<
  [string, BigNumber],
  ExecutionCompletedEventObject
>;

export type ExecutionCompletedEventFilter =
  TypedEventFilter<ExecutionCompletedEvent>;

export interface ReentrancyAttemptedEventObject {
  success: boolean;
}
export type ReentrancyAttemptedEvent = TypedEvent<
  [boolean],
  ReentrancyAttemptedEventObject
>;

export type ReentrancyAttemptedEventFilter =
  TypedEventFilter<ReentrancyAttemptedEvent>;

export interface ReentrantPostIntentHook extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReentrantPostIntentHookInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    attemptReentry(overrides?: CallOverrides): Promise<[boolean]>;

    execute(
      _intent: IOrchestrator.IntentStruct,
      _amountNetFees: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getReentrancyAttempts(overrides?: CallOverrides): Promise<[BigNumber]>;

    orchestrator(overrides?: CallOverrides): Promise<[string]>;

    reentrancyAttempts(overrides?: CallOverrides): Promise<[BigNumber]>;

    setAttemptReentry(
      _attempt: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFulfillParams(
      paymentProof: PromiseOrValue<BytesLike>,
      intentHash: PromiseOrValue<BytesLike>,
      verificationData: PromiseOrValue<BytesLike>,
      postIntentHookData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    storedFulfillParams(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string] & {
        paymentProof: string;
        intentHash: string;
        verificationData: string;
        postIntentHookData: string;
      }
    >;

    usdc(overrides?: CallOverrides): Promise<[string]>;
  };

  attemptReentry(overrides?: CallOverrides): Promise<boolean>;

  execute(
    _intent: IOrchestrator.IntentStruct,
    _amountNetFees: PromiseOrValue<BigNumberish>,
    arg2: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getReentrancyAttempts(overrides?: CallOverrides): Promise<BigNumber>;

  orchestrator(overrides?: CallOverrides): Promise<string>;

  reentrancyAttempts(overrides?: CallOverrides): Promise<BigNumber>;

  setAttemptReentry(
    _attempt: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFulfillParams(
    paymentProof: PromiseOrValue<BytesLike>,
    intentHash: PromiseOrValue<BytesLike>,
    verificationData: PromiseOrValue<BytesLike>,
    postIntentHookData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  storedFulfillParams(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, string] & {
      paymentProof: string;
      intentHash: string;
      verificationData: string;
      postIntentHookData: string;
    }
  >;

  usdc(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    attemptReentry(overrides?: CallOverrides): Promise<boolean>;

    execute(
      _intent: IOrchestrator.IntentStruct,
      _amountNetFees: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    getReentrancyAttempts(overrides?: CallOverrides): Promise<BigNumber>;

    orchestrator(overrides?: CallOverrides): Promise<string>;

    reentrancyAttempts(overrides?: CallOverrides): Promise<BigNumber>;

    setAttemptReentry(
      _attempt: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFulfillParams(
      paymentProof: PromiseOrValue<BytesLike>,
      intentHash: PromiseOrValue<BytesLike>,
      verificationData: PromiseOrValue<BytesLike>,
      postIntentHookData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    storedFulfillParams(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, string] & {
        paymentProof: string;
        intentHash: string;
        verificationData: string;
        postIntentHookData: string;
      }
    >;

    usdc(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ExecutionCompleted(address,uint256)"(
      recipient?: null,
      amount?: null
    ): ExecutionCompletedEventFilter;
    ExecutionCompleted(
      recipient?: null,
      amount?: null
    ): ExecutionCompletedEventFilter;

    "ReentrancyAttempted(bool)"(success?: null): ReentrancyAttemptedEventFilter;
    ReentrancyAttempted(success?: null): ReentrancyAttemptedEventFilter;
  };

  estimateGas: {
    attemptReentry(overrides?: CallOverrides): Promise<BigNumber>;

    execute(
      _intent: IOrchestrator.IntentStruct,
      _amountNetFees: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getReentrancyAttempts(overrides?: CallOverrides): Promise<BigNumber>;

    orchestrator(overrides?: CallOverrides): Promise<BigNumber>;

    reentrancyAttempts(overrides?: CallOverrides): Promise<BigNumber>;

    setAttemptReentry(
      _attempt: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFulfillParams(
      paymentProof: PromiseOrValue<BytesLike>,
      intentHash: PromiseOrValue<BytesLike>,
      verificationData: PromiseOrValue<BytesLike>,
      postIntentHookData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    storedFulfillParams(overrides?: CallOverrides): Promise<BigNumber>;

    usdc(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    attemptReentry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    execute(
      _intent: IOrchestrator.IntentStruct,
      _amountNetFees: PromiseOrValue<BigNumberish>,
      arg2: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getReentrancyAttempts(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    orchestrator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reentrancyAttempts(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAttemptReentry(
      _attempt: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFulfillParams(
      paymentProof: PromiseOrValue<BytesLike>,
      intentHash: PromiseOrValue<BytesLike>,
      verificationData: PromiseOrValue<BytesLike>,
      postIntentHookData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    storedFulfillParams(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    usdc(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
