/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ReentrantRateManagerMockInterface extends utils.Interface {
  functions: {
    "attackRateManagerId()": FunctionFragment;
    "escrow()": FunctionFragment;
    "getFee(bytes32)": FunctionFragment;
    "getRate(bytes32,address,uint256,bytes32,bytes32)": FunctionFragment;
    "isRateManager(bytes32)": FunctionFragment;
    "onDepositOptIn(uint256,bytes32)": FunctionFragment;
    "reentryAttempted()": FunctionFragment;
    "reentrySucceeded()": FunctionFragment;
    "setAttackParams(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "attackRateManagerId"
      | "escrow"
      | "getFee"
      | "getRate"
      | "isRateManager"
      | "onDepositOptIn"
      | "reentryAttempted"
      | "reentrySucceeded"
      | "setAttackParams"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "attackRateManagerId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getFee",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRate",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isRateManager",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "onDepositOptIn",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "reentryAttempted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reentrySucceeded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAttackParams",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "attackRateManagerId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRateManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onDepositOptIn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reentryAttempted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reentrySucceeded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttackParams",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ReentrantRateManagerMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReentrantRateManagerMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    attackRateManagerId(overrides?: CallOverrides): Promise<[string]>;

    escrow(overrides?: CallOverrides): Promise<[string]>;

    getFee(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;

    getRate(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    isRateManager(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    reentryAttempted(overrides?: CallOverrides): Promise<[boolean]>;

    reentrySucceeded(overrides?: CallOverrides): Promise<[boolean]>;

    setAttackParams(
      _attackRateManagerId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  attackRateManagerId(overrides?: CallOverrides): Promise<string>;

  escrow(overrides?: CallOverrides): Promise<string>;

  getFee(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber]>;

  getRate(
    arg0: PromiseOrValue<BytesLike>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    arg4: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isRateManager(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  onDepositOptIn(
    _depositId: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  reentryAttempted(overrides?: CallOverrides): Promise<boolean>;

  reentrySucceeded(overrides?: CallOverrides): Promise<boolean>;

  setAttackParams(
    _attackRateManagerId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    attackRateManagerId(overrides?: CallOverrides): Promise<string>;

    escrow(overrides?: CallOverrides): Promise<string>;

    getFee(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;

    getRate(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRateManager(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    reentryAttempted(overrides?: CallOverrides): Promise<boolean>;

    reentrySucceeded(overrides?: CallOverrides): Promise<boolean>;

    setAttackParams(
      _attackRateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    attackRateManagerId(overrides?: CallOverrides): Promise<BigNumber>;

    escrow(overrides?: CallOverrides): Promise<BigNumber>;

    getFee(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRate(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRateManager(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    reentryAttempted(overrides?: CallOverrides): Promise<BigNumber>;

    reentrySucceeded(overrides?: CallOverrides): Promise<BigNumber>;

    setAttackParams(
      _attackRateManagerId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    attackRateManagerId(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    escrow(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFee(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRate(
      arg0: PromiseOrValue<BytesLike>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      arg4: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRateManager(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    reentryAttempted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reentrySucceeded(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAttackParams(
      _attackRateManagerId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
