/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ChainlinkOracleAdapter__factory } from "./ChainlinkOracleAdapter__factory";
export { PythOracleAdapter__factory } from "./PythOracleAdapter__factory";
