/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IOrchestrator {
  export type IntentStruct = {
    owner: PromiseOrValue<string>;
    to: PromiseOrValue<string>;
    escrow: PromiseOrValue<string>;
    depositId: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    timestamp: PromiseOrValue<BigNumberish>;
    paymentMethod: PromiseOrValue<BytesLike>;
    fiatCurrency: PromiseOrValue<BytesLike>;
    conversionRate: PromiseOrValue<BigNumberish>;
    payeeId: PromiseOrValue<BytesLike>;
    referrer: PromiseOrValue<string>;
    referrerFee: PromiseOrValue<BigNumberish>;
    postIntentHook: PromiseOrValue<string>;
    data: PromiseOrValue<BytesLike>;
  };

  export type IntentStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    string,
    BigNumber,
    string,
    string
  ] & {
    owner: string;
    to: string;
    escrow: string;
    depositId: BigNumber;
    amount: BigNumber;
    timestamp: BigNumber;
    paymentMethod: string;
    fiatCurrency: string;
    conversionRate: BigNumber;
    payeeId: string;
    referrer: string;
    referrerFee: BigNumber;
    postIntentHook: string;
    data: string;
  };
}

export declare namespace IEscrow {
  export type RangeStruct = {
    min: PromiseOrValue<BigNumberish>;
    max: PromiseOrValue<BigNumberish>;
  };

  export type RangeStructOutput = [BigNumber, BigNumber] & {
    min: BigNumber;
    max: BigNumber;
  };

  export type DepositStruct = {
    depositor: PromiseOrValue<string>;
    delegate: PromiseOrValue<string>;
    token: PromiseOrValue<string>;
    intentAmountRange: IEscrow.RangeStruct;
    acceptingIntents: PromiseOrValue<boolean>;
    remainingDeposits: PromiseOrValue<BigNumberish>;
    outstandingIntentAmount: PromiseOrValue<BigNumberish>;
    intentGuardian: PromiseOrValue<string>;
    retainOnEmpty: PromiseOrValue<boolean>;
  };

  export type DepositStructOutput = [
    string,
    string,
    string,
    IEscrow.RangeStructOutput,
    boolean,
    BigNumber,
    BigNumber,
    string,
    boolean
  ] & {
    depositor: string;
    delegate: string;
    token: string;
    intentAmountRange: IEscrow.RangeStructOutput;
    acceptingIntents: boolean;
    remainingDeposits: BigNumber;
    outstandingIntentAmount: BigNumber;
    intentGuardian: string;
    retainOnEmpty: boolean;
  };

  export type DepositPaymentMethodDataStruct = {
    intentGatingService: PromiseOrValue<string>;
    payeeDetails: PromiseOrValue<BytesLike>;
    data: PromiseOrValue<BytesLike>;
  };

  export type DepositPaymentMethodDataStructOutput = [
    string,
    string,
    string
  ] & { intentGatingService: string; payeeDetails: string; data: string };

  export type CurrencyStruct = {
    code: PromiseOrValue<BytesLike>;
    minConversionRate: PromiseOrValue<BigNumberish>;
  };

  export type CurrencyStructOutput = [string, BigNumber] & {
    code: string;
    minConversionRate: BigNumber;
  };
}

export declare namespace IProtocolViewer {
  export type PaymentMethodDataViewStruct = {
    paymentMethod: PromiseOrValue<BytesLike>;
    verificationData: IEscrow.DepositPaymentMethodDataStruct;
    currencies: IEscrow.CurrencyStruct[];
  };

  export type PaymentMethodDataViewStructOutput = [
    string,
    IEscrow.DepositPaymentMethodDataStructOutput,
    IEscrow.CurrencyStructOutput[]
  ] & {
    paymentMethod: string;
    verificationData: IEscrow.DepositPaymentMethodDataStructOutput;
    currencies: IEscrow.CurrencyStructOutput[];
  };

  export type DepositViewStruct = {
    depositId: PromiseOrValue<BigNumberish>;
    deposit: IEscrow.DepositStruct;
    availableLiquidity: PromiseOrValue<BigNumberish>;
    paymentMethods: IProtocolViewer.PaymentMethodDataViewStruct[];
    intentHashes: PromiseOrValue<BytesLike>[];
  };

  export type DepositViewStructOutput = [
    BigNumber,
    IEscrow.DepositStructOutput,
    BigNumber,
    IProtocolViewer.PaymentMethodDataViewStructOutput[],
    string[]
  ] & {
    depositId: BigNumber;
    deposit: IEscrow.DepositStructOutput;
    availableLiquidity: BigNumber;
    paymentMethods: IProtocolViewer.PaymentMethodDataViewStructOutput[];
    intentHashes: string[];
  };

  export type IntentViewStruct = {
    intentHash: PromiseOrValue<BytesLike>;
    intent: IOrchestrator.IntentStruct;
    deposit: IProtocolViewer.DepositViewStruct;
  };

  export type IntentViewStructOutput = [
    string,
    IOrchestrator.IntentStructOutput,
    IProtocolViewer.DepositViewStructOutput
  ] & {
    intentHash: string;
    intent: IOrchestrator.IntentStructOutput;
    deposit: IProtocolViewer.DepositViewStructOutput;
  };
}

export interface IProtocolViewerInterface extends utils.Interface {
  functions: {
    "getAccountIntents(address)": FunctionFragment;
    "getDepositFromIds(uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getAccountIntents" | "getDepositFromIds"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAccountIntents",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositFromIds",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAccountIntents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositFromIds",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IProtocolViewer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IProtocolViewerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAccountIntents(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [IProtocolViewer.IntentViewStructOutput[]] & {
        intentViews: IProtocolViewer.IntentViewStructOutput[];
      }
    >;

    getDepositFromIds(
      _depositIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[IProtocolViewer.DepositViewStructOutput[]]>;
  };

  getAccountIntents(
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<IProtocolViewer.IntentViewStructOutput[]>;

  getDepositFromIds(
    _depositIds: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<IProtocolViewer.DepositViewStructOutput[]>;

  callStatic: {
    getAccountIntents(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<IProtocolViewer.IntentViewStructOutput[]>;

    getDepositFromIds(
      _depositIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<IProtocolViewer.DepositViewStructOutput[]>;
  };

  filters: {};

  estimateGas: {
    getAccountIntents(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDepositFromIds(
      _depositIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAccountIntents(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDepositFromIds(
      _depositIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
