/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IRateManagerInterface extends utils.Interface {
  functions: {
    "getFee(bytes32)": FunctionFragment;
    "getRate(bytes32,address,uint256,bytes32,bytes32)": FunctionFragment;
    "isRateManager(bytes32)": FunctionFragment;
    "onDepositOptIn(uint256,bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getFee"
      | "getRate"
      | "isRateManager"
      | "onDepositOptIn"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getFee",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getRate",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isRateManager",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "onDepositOptIn",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRateManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onDepositOptIn",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IRateManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRateManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { recipient: string; fee: BigNumber }>;

    getRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { rate: BigNumber }>;

    isRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { exists: boolean }>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getFee(
    _rateManagerId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { recipient: string; fee: BigNumber }>;

  getRate(
    _rateManagerId: PromiseOrValue<BytesLike>,
    _escrow: PromiseOrValue<string>,
    _depositId: PromiseOrValue<BigNumberish>,
    _paymentMethod: PromiseOrValue<BytesLike>,
    _currencyCode: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  isRateManager(
    _rateManagerId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  onDepositOptIn(
    _depositId: PromiseOrValue<BigNumberish>,
    _rateManagerId: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { recipient: string; fee: BigNumber }>;

    getRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getFee(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRate(
      _rateManagerId: PromiseOrValue<BytesLike>,
      _escrow: PromiseOrValue<string>,
      _depositId: PromiseOrValue<BigNumberish>,
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRateManager(
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onDepositOptIn(
      _depositId: PromiseOrValue<BigNumberish>,
      _rateManagerId: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
