/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface PaymentVerifierRegistryInterface extends utils.Interface {
  functions: {
    "addCurrencies(bytes32,bytes32[])": FunctionFragment;
    "addPaymentMethod(bytes32,address,bytes32[])": FunctionFragment;
    "getCurrencies(bytes32)": FunctionFragment;
    "getPaymentMethods()": FunctionFragment;
    "getVerifier(bytes32)": FunctionFragment;
    "isCurrency(bytes32,bytes32)": FunctionFragment;
    "isPaymentMethod(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "paymentMethods(uint256)": FunctionFragment;
    "removeCurrencies(bytes32,bytes32[])": FunctionFragment;
    "removePaymentMethod(bytes32)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "store(bytes32)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addCurrencies"
      | "addPaymentMethod"
      | "getCurrencies"
      | "getPaymentMethods"
      | "getVerifier"
      | "isCurrency"
      | "isPaymentMethod"
      | "owner"
      | "paymentMethods"
      | "removeCurrencies"
      | "removePaymentMethod"
      | "renounceOwnership"
      | "store"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addCurrencies",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "addPaymentMethod",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrencies",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentMethods",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifier",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "isCurrency",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "isPaymentMethod",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentMethods",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeCurrencies",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removePaymentMethod",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "store",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCurrencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPaymentMethod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentMethods",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isCurrency", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPaymentMethod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentMethods",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeCurrencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePaymentMethod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "store", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "CurrencyAdded(bytes32,bytes32)": EventFragment;
    "CurrencyRemoved(bytes32,bytes32)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PaymentMethodAdded(bytes32)": EventFragment;
    "PaymentMethodRemoved(bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CurrencyAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CurrencyRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PaymentMethodAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PaymentMethodRemoved"): EventFragment;
}

export interface CurrencyAddedEventObject {
  paymentMethod: string;
  currencyCode: string;
}
export type CurrencyAddedEvent = TypedEvent<
  [string, string],
  CurrencyAddedEventObject
>;

export type CurrencyAddedEventFilter = TypedEventFilter<CurrencyAddedEvent>;

export interface CurrencyRemovedEventObject {
  paymentMethod: string;
  currencyCode: string;
}
export type CurrencyRemovedEvent = TypedEvent<
  [string, string],
  CurrencyRemovedEventObject
>;

export type CurrencyRemovedEventFilter = TypedEventFilter<CurrencyRemovedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PaymentMethodAddedEventObject {
  paymentMethod: string;
}
export type PaymentMethodAddedEvent = TypedEvent<
  [string],
  PaymentMethodAddedEventObject
>;

export type PaymentMethodAddedEventFilter =
  TypedEventFilter<PaymentMethodAddedEvent>;

export interface PaymentMethodRemovedEventObject {
  paymentMethod: string;
}
export type PaymentMethodRemovedEvent = TypedEvent<
  [string],
  PaymentMethodRemovedEventObject
>;

export type PaymentMethodRemovedEventFilter =
  TypedEventFilter<PaymentMethodRemovedEvent>;

export interface PaymentVerifierRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PaymentVerifierRegistryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addPaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _verifier: PromiseOrValue<string>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getPaymentMethods(overrides?: CallOverrides): Promise<[string[]]>;

    getVerifier(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isCurrency(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isPaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    paymentMethods(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    removeCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removePaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    store(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { initialized: boolean; verifier: string }>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addCurrencies(
    _paymentMethod: PromiseOrValue<BytesLike>,
    _currencies: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addPaymentMethod(
    _paymentMethod: PromiseOrValue<BytesLike>,
    _verifier: PromiseOrValue<string>,
    _currencies: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getCurrencies(
    _paymentMethod: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getPaymentMethods(overrides?: CallOverrides): Promise<string[]>;

  getVerifier(
    _paymentMethod: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  isCurrency(
    _paymentMethod: PromiseOrValue<BytesLike>,
    _currencyCode: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isPaymentMethod(
    _paymentMethod: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  paymentMethods(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  removeCurrencies(
    _paymentMethod: PromiseOrValue<BytesLike>,
    _currencies: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removePaymentMethod(
    _paymentMethod: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  store(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<[boolean, string] & { initialized: boolean; verifier: string }>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    addPaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _verifier: PromiseOrValue<string>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    getCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getPaymentMethods(overrides?: CallOverrides): Promise<string[]>;

    getVerifier(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    isCurrency(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isPaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    paymentMethods(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    removeCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    removePaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    store(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { initialized: boolean; verifier: string }>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CurrencyAdded(bytes32,bytes32)"(
      paymentMethod?: PromiseOrValue<BytesLike> | null,
      currencyCode?: PromiseOrValue<BytesLike> | null
    ): CurrencyAddedEventFilter;
    CurrencyAdded(
      paymentMethod?: PromiseOrValue<BytesLike> | null,
      currencyCode?: PromiseOrValue<BytesLike> | null
    ): CurrencyAddedEventFilter;

    "CurrencyRemoved(bytes32,bytes32)"(
      paymentMethod?: PromiseOrValue<BytesLike> | null,
      currencyCode?: PromiseOrValue<BytesLike> | null
    ): CurrencyRemovedEventFilter;
    CurrencyRemoved(
      paymentMethod?: PromiseOrValue<BytesLike> | null,
      currencyCode?: PromiseOrValue<BytesLike> | null
    ): CurrencyRemovedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "PaymentMethodAdded(bytes32)"(
      paymentMethod?: PromiseOrValue<BytesLike> | null
    ): PaymentMethodAddedEventFilter;
    PaymentMethodAdded(
      paymentMethod?: PromiseOrValue<BytesLike> | null
    ): PaymentMethodAddedEventFilter;

    "PaymentMethodRemoved(bytes32)"(
      paymentMethod?: PromiseOrValue<BytesLike> | null
    ): PaymentMethodRemovedEventFilter;
    PaymentMethodRemoved(
      paymentMethod?: PromiseOrValue<BytesLike> | null
    ): PaymentMethodRemovedEventFilter;
  };

  estimateGas: {
    addCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addPaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _verifier: PromiseOrValue<string>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPaymentMethods(overrides?: CallOverrides): Promise<BigNumber>;

    getVerifier(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isCurrency(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paymentMethods(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removePaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    store(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addPaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _verifier: PromiseOrValue<string>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPaymentMethods(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVerifier(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCurrency(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencyCode: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paymentMethods(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeCurrencies(
      _paymentMethod: PromiseOrValue<BytesLike>,
      _currencies: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removePaymentMethod(
      _paymentMethod: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    store(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
