export const CANONICAL_STATES = [
  'CREATED',
  'FUNDING',
  'FUNDED',
  'PROOF_SUBMITTED',
  'VERIFIED',
  'SWAPPING',
  'READY_TO_WITHDRAW',
  'WITHDRAWING',
  'COMPLETE',
  'FAILED',
  'CANCELED',
  'EXPIRED',
] as const;

export type IntentState = (typeof CANONICAL_STATES)[number];

export const ALLOWED_TRANSITIONS: Record<IntentState, IntentState[]> = {
  CREATED: ['FUNDING', 'CANCELED', 'EXPIRED', 'FAILED'],
  FUNDING: ['FUNDED', 'PROOF_SUBMITTED', 'CANCELED', 'EXPIRED', 'FAILED'],
  FUNDED: ['PROOF_SUBMITTED', 'SWAPPING', 'READY_TO_WITHDRAW', 'COMPLETE', 'FAILED', 'EXPIRED'],
  PROOF_SUBMITTED: ['VERIFIED', 'COMPLETE', 'FAILED', 'EXPIRED'],
  VERIFIED: ['COMPLETE', 'FAILED'],
  SWAPPING: ['READY_TO_WITHDRAW', 'FAILED', 'EXPIRED'],
  READY_TO_WITHDRAW: ['WITHDRAWING', 'COMPLETE', 'FAILED', 'EXPIRED'],
  WITHDRAWING: ['COMPLETE', 'FAILED', 'EXPIRED'],
  COMPLETE: [],
  FAILED: [],
  CANCELED: [],
  EXPIRED: [],
};

export function canTransition(from: IntentState, to: IntentState): boolean {
  return ALLOWED_TRANSITIONS[from].includes(to);
}
