/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  PythMock,
  PythMockInterface,
} from "../../../contracts/mocks/PythMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "getPriceUnsafe",
    outputs: [
      {
        components: [
          {
            internalType: "int64",
            name: "price",
            type: "int64",
          },
          {
            internalType: "uint64",
            name: "conf",
            type: "uint64",
          },
          {
            internalType: "int32",
            name: "expo",
            type: "int32",
          },
          {
            internalType: "uint256",
            name: "publishTime",
            type: "uint256",
          },
        ],
        internalType: "struct IPyth.Price",
        name: "price",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "",
        type: "bytes[]",
      },
    ],
    name: "getUpdateFee",
    outputs: [
      {
        internalType: "uint256",
        name: "feeAmount",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    name: "removePrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "int64",
        name: "price",
        type: "int64",
      },
      {
        internalType: "uint64",
        name: "conf",
        type: "uint64",
      },
      {
        internalType: "int32",
        name: "expo",
        type: "int32",
      },
      {
        internalType: "uint256",
        name: "publishTime",
        type: "uint256",
      },
    ],
    name: "setPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "",
        type: "bytes[]",
      },
    ],
    name: "updatePriceFeeds",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523461001657610333908161001c8239f35b600080fdfe604060808152600436101561001357600080fd5b600090813560e01c80637f2d64751461023d57806396834ad314610161578063d47eed4514610146578063ef9e5e28146101375763fe02dfd61461005657600080fd5b346101335760a0366003190112610133576024358060070b80910361012f5760443567ffffffffffffffff9081811680910361012b57606435918260030b809303610127576001926100a66102c7565b94855260208501928352858501908152606085019260843584526004358852876020528688209551926fffffffffffffffff000000000000000087549251891b16925160801b63ffffffff60801b169316906bffffffffffffffffffffffff60a01b1617171783555191015560016020528120600160ff1982541617905580f35b8580fd5b8480fd5b8280fd5b5080fd5b8261014136610275565b505080f35b50346101335760209061015836610275565b50505160018152f35b50346101335760208060031936011261012f576004358360606101826102c7565b8281528285820152828682015201528084526001825260ff838520541615610209578383916080955280835220916101b86102c7565b918354908160070b948585528185016060600167ffffffffffffffff938487891c168452878901968b1c60030b87520154960195865284519687525116908501525160030b90830152516060820152f35b50606491519062461bcd60e51b82526004820152600e60248201526d19995959081b9bdd08199bdd5b9960921b6044820152fd5b50346101335760203660031901126101335760043582528160205281600182822082815501556001602052812060ff19815416905580f35b9060206003198301126102c25760043567ffffffffffffffff928382116102c257806023830112156102c25781600401359384116102c25760248460051b830101116102c2576024019190565b600080fd5b604051906080820182811067ffffffffffffffff8211176102e757604052565b634e487b7160e01b600052604160045260246000fdfea2646970667358221220434ae339f84301d04df1baefc4b7090a47f270c6794a120d7d714624f984ff0464736f6c63430008120033";

type PythMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PythMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PythMock__factory extends ContractFactory {
  constructor(...args: PythMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<PythMock> {
    return super.deploy(overrides || {}) as Promise<PythMock>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): PythMock {
    return super.attach(address) as PythMock;
  }
  override connect(signer: Signer): PythMock__factory {
    return super.connect(signer) as PythMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PythMockInterface {
    return new utils.Interface(_abi) as PythMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PythMock {
    return new Contract(address, _abi, signerOrProvider) as PythMock;
  }
}
